apiVersion: v1
kind: Service
metadata:
  name: proj1-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 80    # matches containerPort in pod
      nodePort: 31000   # port on your node
