apiVersion: v1
kind: Service
metadata:
  name: proj1-service
spec:
  type: NodePort
  selector:
    app: proj1
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80  
      nodePort: 31000 
